import type {
  Activity,
  ActivityFeedItem,
  AIInsight,
  DiscussionMessage,
  Document,
  Invitation,
  KnowledgeEdge,
  KnowledgeNode,
  Notification,
  Project,
  Recommendation,
  Task,
  User,
} from "./types";

export const CURRENT_USER_ID = "u1";

export const users: User[] = [
  {
    id: "u1",
    name: "Ritheesh Kumar",
    email: "ritheesh@college.edu",
    role: "Student",
    organization: "Kumaraguru College of Technology",
    year: "3rd Year",
    department: "Computer Science",
    skills: ["Python", "AI/ML", "Web Development", "Cybersecurity"],
    github: "https://github.com/ritheesh",
    linkedin: "https://linkedin.com/in/ritheesh",
    portfolio: "https://ritheesh.dev",
    interests: ["Collaborative tooling", "AI for education", "Knowledge sharing"],
    previousProjects: ["Campus Event Platform", "Phishing Awareness Bot"],
    bio: "Building intelligent systems that help teams learn together.",
  },
  {
    id: "u2",
    name: "Priya Sharma",
    email: "priya@college.edu",
    role: "Student",
    organization: "Kumaraguru College of Technology",
    year: "3rd Year",
    department: "Computer Science",
    skills: ["Data Science", "Python", "SQL", "UI/UX"],
    github: "https://github.com/priyasharma",
    linkedin: "https://linkedin.com/in/priyasharma",
    interests: ["ML pipelines", "Data visualization"],
    previousProjects: ["Student Grade Predictor"],
  },
  {
    id: "u3",
    name: "Arun Krishnan",
    email: "arun@college.edu",
    role: "Student",
    organization: "PSG College of Technology",
    year: "4th Year",
    department: "Information Technology",
    skills: ["Java", "Cybersecurity", "Network Security", "Python"],
    github: "https://github.com/arunkr",
    linkedin: "https://linkedin.com/in/arunkr",
    interests: ["Collaborative facilitation", "Knowledge synthesis"],
    previousProjects: ["Network Packet Analyzer"],
  },
  {
    id: "u4",
    name: "Karthik Menon",
    email: "karthik@college.edu",
    role: "Student",
    organization: "Kumaraguru College of Technology",
    year: "3rd Year",
    department: "AI & Data Science",
    skills: ["AI/ML", "Python", "Deep Learning", "Data Science"],
    github: "https://github.com/karthikm",
    interests: ["Model evaluation", "Feature engineering"],
    previousProjects: ["Sentiment Analyzer"],
  },
  {
    id: "u5",
    name: "Divya Nair",
    email: "divya@college.edu",
    role: "Student",
    organization: "Amrita University",
    year: "2nd Year",
    department: "Computer Science",
    skills: ["Web Development", "UI/UX", "React", "TypeScript"],
    github: "https://github.com/divyanair",
    linkedin: "https://linkedin.com/in/divyanair",
    interests: ["Design systems", "Frontend architecture"],
    previousProjects: ["College Club Portal"],
  },
  {
    id: "u6",
    name: "Sneha Patel",
    email: "sneha@college.edu",
    role: "Student",
    organization: "VIT Chennai",
    year: "3rd Year",
    department: "Computer Science",
    skills: ["Java", "Spring Boot", "SQL", "System Design"],
    github: "https://github.com/snehap",
    interests: ["Backend APIs", "Distributed systems"],
    previousProjects: ["Library Management API"],
  },
  {
    id: "u7",
    name: "Rahul Desai",
    email: "rahul@college.edu",
    role: "Student",
    organization: "NIT Trichy",
    year: "4th Year",
    department: "Electronics",
    skills: ["IoT", "Python", "Embedded Systems", "C++"],
    interests: ["Edge computing", "Sensor networks"],
    previousProjects: ["Smart Irrigation"],
  },
];

export const projects: Project[] = [
  {
    id: "p1",
    name: "Collaborative Learning Intelligence",
    description:
      "An opt-in team workspace that connects discussions, shared documents, and task contributions to surface knowledge gaps and recommend better ways to collaborate.",
    category: "AI/ML",
    skillsRequired: ["Python", "AI/ML", "NLP", "UI/UX"],
    duration: "12 weeks",
    teamSize: 5,
    visibility: "public",
    status: "active",
    progress: 62,
    ownerId: "u1",
    members: [
      { userId: "u1", role: "Project Lead", contribution: 28, joinedAt: "2026-08-01" },
      { userId: "u2", role: "Learning Data", contribution: 24, joinedAt: "2026-08-02" },
      { userId: "u3", role: "Facilitation Research", contribution: 22, joinedAt: "2026-08-03" },
      { userId: "u4", role: "NLP Engineer", contribution: 18, joinedAt: "2026-08-05" },
      { userId: "u5", role: "Product Design", contribution: 8, joinedAt: "2026-08-10" },
    ],
    createdAt: "2026-08-01T10:00:00Z",
    lastActivity: "2026-09-25T08:30:00Z",
    college: "Kumaraguru College of Technology",
    lookingForMembers: false,
    milestones: [
      { id: "m1", title: "Define consent and data scope", dueDate: "2026-08-20", completed: true },
      { id: "m2", title: "Map discussion and task signals", dueDate: "2026-09-05", completed: true },
      { id: "m3", title: "Synthesize team knowledge", dueDate: "2026-09-20", completed: false },
      { id: "m4", title: "Collaboration insights dashboard", dueDate: "2026-10-10", completed: false },
      { id: "m5", title: "Pilot and team feedback", dueDate: "2026-10-30", completed: false },
    ],
  },
  {
    id: "p2",
    name: "Campus Knowledge Graph",
    description:
      "A semantic knowledge graph connecting courses, projects, and student skills to recommend learning pathways.",
    category: "AI/ML",
    skillsRequired: ["Python", "Graph Databases", "NLP", "Web Development"],
    duration: "10 weeks",
    teamSize: 4,
    visibility: "public",
    status: "planning",
    progress: 18,
    ownerId: "u2",
    members: [
      { userId: "u2", role: "Lead", contribution: 40, joinedAt: "2026-09-01" },
      { userId: "u5", role: "Frontend", contribution: 35, joinedAt: "2026-09-02" },
      { userId: "u1", role: "ML Contributor", contribution: 25, joinedAt: "2026-09-08" },
    ],
    createdAt: "2026-09-01T09:00:00Z",
    lastActivity: "2026-09-24T16:00:00Z",
    college: "Kumaraguru College of Technology",
    lookingForMembers: true,
    milestones: [
      { id: "m6", title: "Ontology design", dueDate: "2026-09-15", completed: true },
      { id: "m7", title: "Entity extraction pipeline", dueDate: "2026-09-30", completed: false },
    ],
  },
  {
    id: "p3",
    name: "Secure Chat for Student Clubs",
    description:
      "End-to-end encrypted messaging for campus clubs with moderation tools and event coordination.",
    category: "Web Development",
    skillsRequired: ["TypeScript", "Web Development", "Cryptography", "UI/UX"],
    duration: "8 weeks",
    teamSize: 4,
    visibility: "public",
    status: "active",
    progress: 45,
    ownerId: "u5",
    members: [
      { userId: "u5", role: "Lead", contribution: 38, joinedAt: "2026-08-15" },
      { userId: "u6", role: "Backend", contribution: 32, joinedAt: "2026-08-16" },
      { userId: "u7", role: "Security", contribution: 30, joinedAt: "2026-08-20" },
    ],
    createdAt: "2026-08-15T11:00:00Z",
    lastActivity: "2026-09-23T12:00:00Z",
    college: "Amrita University",
    lookingForMembers: true,
    milestones: [
      { id: "m8", title: "Auth & E2E scaffold", dueDate: "2026-09-01", completed: true },
      { id: "m9", title: "Club channels MVP", dueDate: "2026-09-25", completed: false },
    ],
  },
  {
    id: "p4",
    name: "Smart Attendance Edge System",
    description:
      "IoT-based attendance with face recognition at the edge, privacy-preserving storage, and faculty dashboards.",
    category: "IoT",
    skillsRequired: ["IoT", "Python", "Computer Vision", "Embedded Systems"],
    duration: "14 weeks",
    teamSize: 5,
    visibility: "public",
    status: "active",
    progress: 33,
    ownerId: "u7",
    members: [
      { userId: "u7", role: "Lead", contribution: 45, joinedAt: "2026-07-20" },
      { userId: "u4", role: "CV Engineer", contribution: 30, joinedAt: "2026-07-25" },
      { userId: "u6", role: "Backend", contribution: 25, joinedAt: "2026-08-01" },
    ],
    createdAt: "2026-07-20T08:00:00Z",
    lastActivity: "2026-09-22T09:00:00Z",
    college: "NIT Trichy",
    lookingForMembers: true,
    milestones: [
      { id: "m10", title: "Hardware prototype", dueDate: "2026-08-30", completed: true },
      { id: "m11", title: "On-device inference", dueDate: "2026-09-28", completed: false },
    ],
  },
  {
    id: "p5",
    name: "Peer Review Assistant",
    description:
      "AI assistant that structures peer feedback for coding assignments while preserving instructor control.",
    category: "EdTech",
    skillsRequired: ["AI/ML", "NLP", "Web Development", "Education"],
    duration: "9 weeks",
    teamSize: 3,
    visibility: "private",
    status: "planning",
    progress: 12,
    ownerId: "u3",
    members: [
      { userId: "u3", role: "Lead", contribution: 55, joinedAt: "2026-09-10" },
      { userId: "u2", role: "NLP", contribution: 45, joinedAt: "2026-09-12" },
    ],
    createdAt: "2026-09-10T14:00:00Z",
    lastActivity: "2026-09-21T18:00:00Z",
    college: "PSG College of Technology",
    lookingForMembers: false,
    milestones: [
      { id: "m12", title: "Rubric schema", dueDate: "2026-09-25", completed: false },
    ],
  },
];

export const tasks: Task[] = [
  {
    id: "t1",
    projectId: "p1",
    title: "Define opt-in discussion data boundaries",
    description: "Document which shared project discussions can be analyzed and how members can opt out.",
    assigneeId: "u2",
    status: "completed",
    priority: "high",
    dueDate: "2026-09-10",
    tags: ["consent", "privacy"],
  },
  {
    id: "t2",
    projectId: "p1",
    title: "Map contribution signals across project work",
    assigneeId: "u4",
    status: "completed",
    priority: "high",
    dueDate: "2026-09-12",
    tags: ["contributions", "analysis"],
  },
  {
    id: "t3",
    projectId: "p1",
    title: "Summarize decisions and unanswered questions",
    description: "Connect discussion themes with shared notes and highlight points the team has not resolved.",
    assigneeId: "u4",
    status: "in_progress",
    priority: "high",
    dueDate: "2026-09-28",
    tags: ["discussion", "synthesis"],
    aiSuggested: true,
  },
  {
    id: "t4",
    projectId: "p1",
    title: "Review participation balance with the team",
    assigneeId: "u3",
    status: "review",
    priority: "medium",
    dueDate: "2026-09-26",
    tags: ["participation", "review"],
  },
  {
    id: "t5",
    projectId: "p1",
    title: "Design a clear knowledge-flow view",
    assigneeId: "u5",
    status: "todo",
    priority: "medium",
    dueDate: "2026-09-30",
    tags: ["ui", "knowledge-flow"],
  },
  {
    id: "t6",
    projectId: "p1",
    title: "Recommend a cross-team knowledge share",
    assigneeId: "u2",
    status: "todo",
    priority: "high",
    dueDate: "2026-09-29",
    tags: ["recommendations", "knowledge-sharing"],
    aiSuggested: true,
  },
  {
    id: "t7",
    projectId: "p1",
    title: "Draft a neutral collaboration summary",
    assigneeId: "u3",
    status: "backlog",
    priority: "low",
    dueDate: "2026-10-05",
    tags: ["summary", "facilitation"],
  },
  {
    id: "t8",
    projectId: "p1",
    title: "Connect task activity to project milestones",
    assigneeId: "u1",
    status: "backlog",
    priority: "medium",
    tags: ["tasks", "project-health"],
  },
];

export const discussions: DiscussionMessage[] = [
  {
    id: "d1",
    projectId: "p1",
    authorId: "u1",
    content:
      "Team sync: can we connect our discussion notes and task updates in one project summary? We keep repeating decisions when someone misses a meeting.",
    timestamp: "2026-09-24T09:00:00Z",
    topic: "Shared Context",
    reactions: [
      { emoji: "👍", count: 3, reacted: true },
      { emoji: "🔥", count: 1 },
    ],
  },
  {
    id: "d2",
    projectId: "p1",
    authorId: "u4",
    content:
      "I can map the decisions from the last two threads into the shared notes and link each one to its follow-up task.",
    timestamp: "2026-09-24T09:18:00Z",
    topic: "Shared Context",
    reactions: [{ emoji: "👍", count: 2 }],
  },
  {
    id: "d3",
    projectId: "p1",
    authorId: "u2",
    content:
      "Before we analyze anything, we should be explicit about consent: only project discussions, shared documents, and task activity that members agree to include.",
    timestamp: "2026-09-24T10:05:00Z",
    topic: "Consent & Privacy",
    reactions: [{ emoji: "💡", count: 4, reacted: true }],
  },
  {
    id: "d4",
    projectId: "p1",
    authorId: "u3",
    content:
      "Participation should not become a score. The insight should show where context is concentrated and suggest a helpful next activity, without labeling a teammate.",
    timestamp: "2026-09-24T11:22:00Z",
    topic: "Participation Balance",
    reactions: [{ emoji: "🎯", count: 3 }],
  },
  {
    id: "d5",
    projectId: "p1",
    authorId: "u5",
    content:
      "I sketched the insight view. It should show connected topics, open questions, and a practical peer-review suggestion in plain language.",
    timestamp: "2026-09-24T14:40:00Z",
    topic: "Product Design",
    reactions: [{ emoji: "🎨", count: 2 }],
  },
  {
    id: "d6",
    projectId: "p1",
    authorId: "u1",
    content:
      "Decision: summarize only authorized shared project activity. Open: how do we let members correct a summary? Priya, can you review the consent flow with me?",
    timestamp: "2026-09-25T07:15:00Z",
    topic: "Consent & Privacy",
    reactions: [{ emoji: "✅", count: 4, reacted: true }],
  },
];

export const documents: Document[] = [
  {
    id: "doc1",
    projectId: "p1",
    name: "Collaboration Data & Consent.md",
    type: "Markdown",
    uploadedBy: "u1",
    date: "2026-09-10T12:00:00Z",
    status: "final",
    size: "2.4 MB",
    keyTopics: ["Consent", "Data Scope", "Transparency"],
    contentPreview:
      "# Collaboration Data & Consent\n\nMesh analyzes only project activity members have authorized for collaborative learning insights.\n\n## Included sources\n- Shared project discussions and their topics\n- Documents intentionally shared in the workspace\n- Task ownership, status, and project milestones\n\n## Member control\nMembers can review what is included, correct a summary, or withdraw a source. Private messages and personal files are out of scope. Insights describe team patterns and never rank or shame individuals.",
  },
  {
    id: "doc2",
    projectId: "p1",
    name: "Knowledge Exchange Findings.md",
    type: "Markdown",
    uploadedBy: "u2",
    date: "2026-09-18T09:30:00Z",
    status: "reviewed",
    size: "48 KB",
    keyTopics: ["Knowledge Flow", "Participation", "Open Questions"],
    contentPreview:
      "# Knowledge Exchange Findings\n\nAuthor: Priya Sharma\n\n### What is working\n- Decisions are captured in project discussions and linked to tasks.\n- Shared notes help teammates catch up asynchronously.\n\n### Where context gets stuck\n- Two design decisions currently rely on one teammate's notes.\n- A few open questions appear in chat but not in the project summary.\n\n### Suggested next step\nHost a short peer review where another teammate presents the current decision log and invites corrections.",
  },
  {
    id: "doc3",
    projectId: "p1",
    name: "Team Contribution Snapshot.csv",
    type: "Spreadsheet",
    uploadedBy: "u4",
    date: "2026-09-20T16:00:00Z",
    status: "final",
    size: "312 KB",
    keyTopics: ["Task Activity", "Discussion Themes", "Coverage"],
    contentPreview:
      "# Team Contribution Snapshot\n\n| Signal | This sprint | Context |\n| :--- | :--- | :--- |\n| Shared discussion topics | 6 | Includes consented project threads |\n| Decisions linked to tasks | 4 | Two decisions need a second reviewer |\n| Shared documents updated | 3 | One summary is awaiting review |\n| Teammates with active tasks | 5 of 5 | Ownership is spread across the team |\n\nUse these signals to guide a conversation, not to score individuals.",
  },
  {
    id: "doc4",
    projectId: "p1",
    name: "Open Questions & Decisions.docx",
    type: "Document",
    uploadedBy: "u3",
    date: "2026-09-22T11:00:00Z",
    status: "draft",
    size: "180 KB",
    keyTopics: ["Decisions", "Unresolved Topics", "Peer Review"],
    contentPreview:
      "# Open Questions & Decisions\n\nFacilitator: Arun Krishnan\n\n### Decisions made\n- Only member-authorized workspace activity is included in analysis.\n- Summaries link back to the discussion or document that supports them.\n\n### Still unresolved\n- How should a teammate suggest a correction to a generated summary?\n- Which activity best helps new members contribute context?\n\nNext step: Invite a teammate who has not reviewed the notes to lead a short peer review.",
  },
  {
    id: "doc5",
    projectId: "p1",
    name: "Learning Insights Wireframes.fig",
    type: "Design",
    uploadedBy: "u5",
    date: "2026-09-23T15:20:00Z",
    status: "draft",
    size: "4.1 MB",
    keyTopics: ["UI Wireframes", "Insight Sources", "Recommendations"],
    contentPreview:
      "# Learning Insights Dashboard\n\nDesigner: Divya Nair\n\n### Screen Components\n1. **Knowledge Flow:** Show how shared topics connect across discussions and documents.\n2. **Collective Summary:** Highlight decisions, evidence, and open questions with source links.\n3. **Collaboration Activities:** Suggest peer review, knowledge sharing, or pair work with a clear reason.\n4. **Privacy Controls:** Make analyzed sources visible and easy to review.",
  },
];

export const insights: AIInsight[] = [
  {
    id: "i1",
    projectId: "p1",
    type: "knowledge_concentration",
    title: "Knowledge Concentration",
    explanation:
      "Several project decisions currently rely on one teammate's notes. Sharing that context would help others contribute and reduce handoff risk.",
    evidence: [
      "Two decisions in the shared discussion threads have one primary contributor",
      "The latest project summary has not yet been reviewed by another teammate",
      "Related follow-up tasks do not yet link back to the decision notes",
    ],
    suggestedAction: "Invite a second teammate to co-present the decision log in a 15-minute knowledge share.",
    severity: "attention",
    createdAt: "2026-09-25T06:00:00Z",
  },
  {
    id: "i2",
    projectId: "p1",
    type: "collaboration_gap",
    title: "Collaboration Gap",
    explanation:
      "Two teammates have not yet contributed to the open project questions.",
    evidence: [
      "Two teammates have not replied to the latest decision thread",
      "Their active tasks focus on product design and facilitation",
      "Few links currently connect their work to the open questions",
    ],
    suggestedAction: "Invite them to review the collective summary and add missing context.",
    severity: "info",
    createdAt: "2026-09-25T06:05:00Z",
  },
  {
    id: "i3",
    projectId: "p1",
    type: "unresolved_topic",
    title: "Unresolved Topic",
    explanation:
      "A consent-flow question appears in the discussion but has not been captured in the decision log.",
    evidence: [
      "The latest thread asks how members can correct generated summaries",
      "No decision is recorded in the shared project notes",
      "The consent review task has no assigned second reviewer",
    ],
    suggestedAction: "Run a short decision discussion and record the member correction flow.",
    severity: "attention",
    createdAt: "2026-09-25T06:10:00Z",
  },
  {
    id: "i4",
    projectId: "p1",
    type: "project_risk",
    title: "Project Risk",
    explanation:
      "The team has not assigned a reviewer for its privacy and consent summary.",
    evidence: [
      "The correction flow remains open in the consent discussion",
      "The second-review task is still in To Do",
      "The knowledge synthesis milestone depends on that review",
    ],
    suggestedAction: "Pair the project lead with a second reviewer and close the consent question together.",
    severity: "urgent",
    createdAt: "2026-09-25T06:15:00Z",
  },
];

export const recommendations: Recommendation[] = [
  {
    id: "r1",
    projectId: "p1",
    type: "knowledge_sharing",
    title: "Knowledge Sharing Session",
    why: "Project decisions are concentrated in one teammate's notes and need a second voice.",
    participants: ["u2", "u4", "u5"],
    duration: "15 minutes",
    status: "pending",
  },
  {
    id: "r2",
    projectId: "p1",
    type: "research_comparison",
    title: "Research Comparison",
    why: "The team has an open consent question without a recorded decision.",
    participants: ["u1", "u3", "u4"],
    duration: "30 minutes",
    status: "pending",
  },
  {
    id: "r3",
    projectId: "p1",
    type: "pair_programming",
    title: "Pair Programming",
    why: "A paired review can connect the summary workflow to the consent controls.",
    participants: ["u2", "u4"],
    duration: "45 minutes",
    status: "pending",
  },
  {
    id: "r4",
    projectId: "p1",
    type: "peer_review",
    title: "Peer Review",
    why: "The shared decision log needs context from product design and facilitation.",
    participants: ["u3", "u1", "u5"],
    duration: "20 minutes",
    status: "pending",
  },
];

export const invitations: Invitation[] = [
  {
    id: "inv1",
    type: "incoming",
    projectId: "p3",
    projectName: "Secure Chat for Student Clubs",
    fromUserId: "u5",
    toUserId: "u1",
    message: "We need someone with cybersecurity + frontend overlap.",
    createdAt: "2026-09-24T08:00:00Z",
    status: "pending",
  },
  {
    id: "inv2",
    type: "incoming",
    projectId: "p4",
    projectName: "Smart Attendance Edge System",
    fromUserId: "u7",
    toUserId: "u1",
    message: "Arun suggested you for the ML inference piece.",
    createdAt: "2026-09-23T19:00:00Z",
    status: "pending",
  },
  {
    id: "inv3",
    type: "join_request",
    projectId: "p1",
    projectName: "Collaborative Learning Intelligence",
    fromUserId: "u6",
    toUserId: "u1",
    message: "I can help with the backend API and model serving.",
    createdAt: "2026-09-25T05:00:00Z",
    status: "pending",
  },
];

export const notifications: Notification[] = [
  {
    id: "n1",
    type: "insight",
    title: "New AI insight generated",
    body: "A few project decisions need a second teammate's perspective.",
    read: false,
    createdAt: "2026-09-25T06:00:00Z",
    href: "/projects/p1/intelligence",
  },
  {
    id: "n2",
    type: "invitation",
    title: "Project invitation",
    body: "Divya invited you to Secure Chat for Student Clubs.",
    read: false,
    createdAt: "2026-09-24T08:00:00Z",
    href: "/invitations",
  },
  {
    id: "n3",
    type: "join_request",
    title: "Join request",
    body: "Sneha wants to join Collaborative Learning Intelligence.",
    read: false,
    createdAt: "2026-09-25T05:00:00Z",
    href: "/invitations",
  },
  {
    id: "n4",
    type: "task",
    title: "Task assigned",
    body: "You were assigned: Connect task activity to project milestones.",
    read: true,
    createdAt: "2026-09-23T10:00:00Z",
    href: "/projects/p1/tasks",
  },
  {
    id: "n5",
    type: "document",
    title: "Document uploaded",
    body: "Priya uploaded Knowledge Exchange Findings.md",
    read: true,
    createdAt: "2026-09-18T09:30:00Z",
    href: "/projects/p1/documents",
  },
  {
    id: "n6",
    type: "mention",
    title: "Mentioned in discussion",
    body: "Karthik mentioned you in Shared Context.",
    read: true,
    createdAt: "2026-09-24T09:18:00Z",
    href: "/projects/p1/discussions",
  },
  {
    id: "n7",
    type: "activity",
    title: "Activity reminder",
    body: "Knowledge sharing session suggested for today.",
    read: false,
    createdAt: "2026-09-25T07:00:00Z",
    href: "/projects/p1/intelligence",
  },
];

export const activityFeed: ActivityFeedItem[] = [
  {
    id: "af1",
    projectId: "p1",
    userId: "u2",
    action: "uploaded Knowledge Exchange Findings.md",
    timestamp: "2026-09-18T09:30:00Z",
  },
  {
    id: "af2",
    projectId: "p1",
    userId: "u4",
    action: "completed task: Map contribution signals across project work",
    timestamp: "2026-09-20T16:10:00Z",
  },
  {
    id: "af3",
    projectId: "p1",
    userId: "u3",
    action: "joined discussion: Participation Balance",
    timestamp: "2026-09-24T11:22:00Z",
  },
  {
    id: "af4",
    projectId: "p1",
    userId: "u1",
    action: "AI generated a new collaboration insight",
    timestamp: "2026-09-25T06:00:00Z",
  },
  {
    id: "af5",
    projectId: "p1",
    userId: "u5",
    action: "uploaded Learning Insights Wireframes.fig",
    timestamp: "2026-09-23T15:20:00Z",
  },
];

export const knowledgeNodes: KnowledgeNode[] = [
  { id: "u1", label: "Ritheesh", role: "Lead", topics: ["Consent", "Coordination"] },
  { id: "u2", label: "Priya", role: "Learning Data", topics: ["Participation", "Decision Log"] },
  { id: "u3", label: "Arun", role: "Facilitation", topics: ["Open Questions", "Peer Review"] },
  { id: "u4", label: "Karthik", role: "NLP", topics: ["Collective Summary", "Discussion Topics"] },
  { id: "u5", label: "Divya", role: "Product Design", topics: ["Knowledge Flow", "Recommendations"] },
];

export const knowledgeEdges: KnowledgeEdge[] = [
  { id: "e1", source: "u2", target: "u1", topic: "Consent scope", strength: 0.9 },
  { id: "e2", source: "u2", target: "u4", topic: "Discussion themes", strength: 0.85 },
  { id: "e3", source: "u2", target: "u3", topic: "Decision notes", strength: 0.4 },
  { id: "e4", source: "u1", target: "u4", topic: "Collective summary", strength: 0.7 },
  { id: "e5", source: "u1", target: "u5", topic: "Insight experience", strength: 0.65 },
  { id: "e6", source: "u4", target: "u3", topic: "Open questions", strength: 0.55 },
  { id: "e7", source: "u3", target: "u1", topic: "Peer review", strength: 0.5 },
  { id: "e8", source: "u5", target: "u1", topic: "Source transparency", strength: 0.45 },
];

export const skillCatalog = [
  "Python",
  "Java",
  "JavaScript",
  "TypeScript",
  "Cybersecurity",
  "AI/ML",
  "Web Development",
  "UI/UX",
  "Data Science",
  "Deep Learning",
  "SQL",
  "React",
  "Node.js",
  "Cloud",
  "DevOps",
  "IoT",
  "NLP",
  "System Design",
  "Graph Databases",
  "Computer Vision",
];

export const categories = [
  "Cybersecurity",
  "AI/ML",
  "Web Development",
  "IoT",
  "EdTech",
  "Mobile",
  "Data Engineering",
  "Blockchain",
];

export const initialActivities: Activity[] = [];

export function getUser(id: string) {
  return users.find((u) => u.id === id);
}

export function getProject(id: string) {
  return projects.find((p) => p.id === id);
}
